version: 2
updates:
  - package-ecosystem: "nuget"
    directories: ["/src"]
    schedule:
      interval: weekly
      day: "friday"
      time: "19:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "dependabot"
    ignore:
      - dependency-name: "Microsoft.EntityFrameworkCore*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Npgsql.EntityFrameworkCore*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Npgsql.OpenTelemetry"
        update-types: ["version-update:semver-major"]
    assignees:
      - "wengwalker"
    target-branch: "develop"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directories: ["/"]
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "dependabot"
    target-branch: "develop"
    versioning-strategy: "auto"
