networks:
  items-network:
    driver: bridge

volumes:
  catalog_db_data:

services:
  catalog-db:
    image: postgres:latest
    container_name: catalog-db-dev
    hostname: catalog-db
    restart: always
    environment:
      - POSTGRES_HOST=${DATABASE_CATALOG_HOST}
      - POSTGRES_PORT=${DATABASE_CATALOG_INNER_PORT}
      - POSTGRES_USER=${DATABASE_CATALOG_USER}
      - POSTGRES_PASSWORD=${DATABASE_CATALOG_PASSWORD}
      - POSTGRES_DB=${DATABASE_CATALOG_DB}
    volumes:
      - catalog_db_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_CATALOG_PORTS:-5432:5432}
    networks:
      - items-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p $${POSTGRES_PORT}"]
      interval: 5s
      timeout: 15s
      retries: 3
      start_period: 10s

  catalog:
    image: ${DOCKER_REGISTRY-}catalog-dev
    container_name: catalog-dev
    hostname: catalog
    build:
      context: .
      dockerfile: Catalog/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - ${CATALOG_PORTS:-8080:8080}
    networks:
      - items-network
    depends_on:
      catalog-db:
        condition: service_healthy
